# NOTE: update this with your service name
service: utefa-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-2
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}
    # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-2:*:*"

functions:
  # /notes

  # - method: POST request
  create-note:
    handler: notes/create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
  list-notes:
    # Defines an HTTP API endpoint that calls the main function in list.js
    # - path: url path is /notes
    # - method: GET request
    handler: notes/list.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: aws_iam
  update-note:
    # Defines an HTTP API endpoint that calls the main function in update.js
    # - path: url path is /notes/{id}
    # - method: PUT request
    handler: notes/update.main
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete-note:
    # Defines an HTTP API endpoint that calls the main function in delete.js
    # - path: url path is /notes/{id}
    # - method: DELETE request
    handler: notes/delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam

  #/votes
  create-vote:
    handler: votes/create.main
    events:
      - http:
          path: votes/create
          method: post
          cors: true
          authorizer: aws_iam
  vote:
    handler: votes/vote.main
    events:
      - http:
          path: votes/vote/{id}/{options}/{userId}
          method: put
          cors: true
          authorizer: aws_iam
  list-votes:
    handler: votes/list.main
    events:
      - http:
          path: votes
          method: get
          cors: true
          authorizer: aws_iam
  delete-vote:
    handler: votes/delete.main
    events:
      - http:
          path: votes/{id}
          method: delete
          cors: true
          authorizer: aws_iam

  #/learningcontent
  list-content:
    handler: learningcontent/list.main
    events:
      - http:
          path: learningcontent
          method: get
          cors: true
          authorizer: aws_iam
  list-public-content:
    handler: learningcontent/listpublic.main
    events:
      - http:
          path: learningcontent/public
          method: get
          cors: true
  create-content:
    handler: learningcontent/create.main
    events:
      - http:
          path: learningcontent
          method: post
          cors: true
          authorizer: aws_iam
  delete-content:
    handler: learningcontent/delete.main
    events:
      - http:
          path: learningcontent/{id}
          method: delete
          cors: true
          authorizer: aws_iam
